name: Build iOS Project

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Xcode  # ← Fixed this step
      uses: actions/setup-xcode@v1  # ← Fixed this line
      with:
        xcode-version: '15.0'
        
    - name: Build project
      run: |
        cd your_project_directory
        make package
